// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNciwtpkVceRotC97F_uZAwzujXyql-7s',
    appId: '1:248617165165:web:e40d5926128c7100493a64',
    messagingSenderId: '248617165165',
    projectId: 'mootocare-f3de8',
    authDomain: 'mootocare-f3de8.firebaseapp.com',
    storageBucket: 'mootocare-f3de8.appspot.com',
    measurementId: 'G-YB7VC58786',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMNr7qV-FDXOPSNXiqxG45gjT925GdMLY',
    appId: '1:248617165165:android:65fad7dd9436f277493a64',
    messagingSenderId: '248617165165',
    projectId: 'mootocare-f3de8',
    storageBucket: 'mootocare-f3de8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUoh-ISC6gqgu_4St8D_N5CqCGa7V2BE',
    appId: '1:248617165165:ios:09cdd154c3f99557493a64',
    messagingSenderId: '248617165165',
    projectId: 'mootocare-f3de8',
    storageBucket: 'mootocare-f3de8.appspot.com',
    iosBundleId: 'com.example.autocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUoh-ISC6gqgu_4St8D_N5CqCGa7V2BE',
    appId: '1:248617165165:ios:3d70a6d755bc9ad3493a64',
    messagingSenderId: '248617165165',
    projectId: 'mootocare-f3de8',
    storageBucket: 'mootocare-f3de8.appspot.com',
    iosBundleId: 'com.example.autocare.RunnerTests',
  );
}
